---
# tasks file for ec2

- name: "provisioning os on aws"
  ec2:
     key_name: "mykey"
     instance_type: "t2.micro"
     image: "ami-0ebc1ac48dfd14136"
     wait: yes
     count: 1
     region: "ap-south-1"
     instance_tags:
       name: "ansible_ec2"
     vpc_subnet_id: "subnet-061d276e"
     group_id: "sg-0275750a36aa3fb24"
     state: present
     assign_public_ip: yes
     aws_access_key: "{{access_key}}"
     aws_secret_key: "{{secret_key}}"
  register: Instance

